routes:
 GET /: Feed.show

  # user api
 user:
   GET register: User.registerForm
   POST register: User.register

   GET login: User.loginForm
   POST login: User.login

   POST logout: User.logout

 shot:
  GET create: Shot.createForm
  POST create: Shot.create
  GET :id-(.+): Shot.show
  POST :id-(.+)/comment: Shot.comment
  POST :id-(.+)/like: Shot.like

 project:
  GET :id-(.+): Project.show

 # more or less a catch all
 GET /:username/: Profile.show

